import localFont from "next/font/local";
import "./globals.css";
import Nav from "./nav/layout";
import Footer from "./components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Health Recipe Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased py-5 flex flex-col gap-y-10 md:gap-y-20`}
      >
        <Nav />
        {children}
       <Footer />
      </body>
    </html>
  );
}
